# Generated by Django 5.1.15 on 2026-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("subadmin", "Subadmin"),
                    ("hiring_manager", "Hiring Manager"),
                    ("trainer", "Trainer"),
                    ("recruiter", "Recruiter"),
                ],
                default="recruiter",
                max_length=20,
            ),
        ),
    ]
