# Generated by Django 5.1.15 on 2026-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_hiring_manager_trainer_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_booking_target",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_call_target",
            field=models.IntegerField(default=0),
        ),
    ]
