# Generated by Django 5.1.4 on 2026-09-09 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "current_bucket",
                    models.CharField(
                        choices=[
                            ("upload_queue", "Upload Queue"),
                            ("fresh", "Fresh Candidates"),
                            ("pipeline", "Pipeline Candidates"),
                        ],
                        db_index=True,
                        default="upload_queue",
                        max_length=20,
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("never_contacted", "Never Contacted"),
                            ("contacted", "Contacted"),
                            ("unanswered", "Unanswered"),
                            ("not_interested", "Not Interested"),
                            ("asked_to_connect_later", "Asked to Connect Later"),
                            ("wrong_number", "Wrong Number"),
                            ("invalid_contact", "Invalid Contact"),
                            ("duplicate", "Duplicate"),
                            ("do_not_contact", "Do Not Contact"),
                            ("follow_up_due", "Follow-up Due"),
                            ("interested", "Interested"),
                            ("screening_scheduled", "Screening Scheduled"),
                            ("screening_completed", "Screening Completed"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("submitted", "Submitted"),
                            ("rejected", "Rejected"),
                            ("selected", "Selected"),
                            ("offer_released", "Offer Released"),
                            ("joined", "Joined"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="never_contacted",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_notes",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruiterAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_history",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "from_recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_recruiter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("imported_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("invalid_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Upload batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("error_type", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("row_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_errors",
                        to="candidates.uploadbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="upload_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="candidates.uploadbatch",
            ),
        ),
        migrations.CreateModel(
            name="CandidateActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("candidate_created", "Candidate Created"),
                            ("candidate_imported", "Candidate Imported"),
                            ("candidate_assigned", "Candidate Assigned"),
                            ("status_changed", "Status Changed"),
                            ("recruiter_changed", "Recruiter Changed"),
                            ("notes_updated", "Notes Updated"),
                            ("calendar_event_created", "Calendar Event Created"),
                            ("email_sent", "Email Sent"),
                            ("zoom_meeting_created", "Zoom Meeting Created"),
                            ("follow_up_updated", "Follow-up Updated"),
                            ("candidate_edited", "Candidate Edited"),
                            ("bucket_changed", "Bucket Changed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "-created_at"],
                        name="candidates__candida_6af1a4_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["current_bucket", "current_status"],
                name="candidates__current_0c8ed0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["assigned_recruiter", "current_bucket"],
                name="candidates__assigne_97e69f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["email", "phone"], name="candidates__email_cf028a_idx"
            ),
        ),
    ]
