# Generated by Django 5.1.4 on 2026-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job_market",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="residential_location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
