# Generated by Django 5.1.15 on 2026-09-11 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_add_location_and_market_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trained_candidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="current_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="current_designation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="experience_years",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("never_contacted", "Never Contacted"),
                    ("contacted", "Contacted"),
                    ("unanswered", "Unanswered"),
                    ("not_interested", "Not Interested"),
                    ("asked_to_connect_later", "Asked to Connect Later"),
                    ("wrong_number", "Wrong Number"),
                    ("invalid_contact", "Invalid Contact"),
                    ("duplicate", "Duplicate"),
                    ("do_not_contact", "Do Not Contact"),
                    ("follow_up_due", "Follow-up Due"),
                    ("interested", "Interested"),
                    ("screening_scheduled", "Screening Scheduled"),
                    ("screening_completed", "Screening Completed"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("round2_scheduled", "Round 2 Scheduled"),
                    ("round2_completed", "Round 2 Completed"),
                    ("observation", "Observation"),
                    ("training", "Training"),
                    ("training_completed", "Training Completed"),
                    ("submitted", "Submitted"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                    ("offer_released", "Offer Released"),
                    ("joined", "Joined"),
                    ("dropped", "Dropped"),
                    ("hired", "Hired"),
                    ("fastgem_uploaded", "FastGem Uploaded"),
                ],
                db_index=True,
                default="never_contacted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="candidateactivitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("candidate_created", "Candidate Created"),
                    ("candidate_imported", "Candidate Imported"),
                    ("candidate_assigned", "Candidate Assigned"),
                    ("status_changed", "Status Changed"),
                    ("recruiter_changed", "Recruiter Changed"),
                    ("notes_updated", "Notes Updated"),
                    ("calendar_event_created", "Calendar Event Created"),
                    ("email_sent", "Email Sent"),
                    ("zoom_meeting_created", "Zoom Meeting Created"),
                    ("follow_up_updated", "Follow-up Updated"),
                    ("candidate_edited", "Candidate Edited"),
                    ("bucket_changed", "Bucket Changed"),
                    ("trainer_assigned", "Trainer Assigned"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
