# Generated by Django 5.1.4 on 2026-09-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="zoom_join_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="interview",
            name="zoom_start_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
