# Generated by Django 5.1.4 on 2026-09-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_add_zoom_rooms_locations_calllogs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_capacity", models.PositiveIntegerField(default=1)),
                ("booked_count", models.PositiveIntegerField(default=0)),
                ("meeting_link", models.URLField(blank=True, max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partially_booked", "Partially Booked"),
                            ("fully_booked", "Fully Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_slots",
                        to="interviews.location",
                    ),
                ),
                (
                    "zoom_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="interviews.zoomaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["date", "status"], name="interviews__date_bf962f_idx"
                    )
                ],
            },
        ),
    ]
