# Generated by Django 5.1.15 on 2026-09-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_add_interview_slot_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="interviews.interviewslot",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="round",
            field=models.CharField(
                choices=[("round_1", "Round 1"), ("round_2", "Round 2")],
                default="round_1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="interviewslot",
            name="round_type",
            field=models.CharField(
                choices=[("round_1", "Round 1"), ("round_2", "Round 2")],
                default="round_1",
                max_length=10,
            ),
        ),
    ]
