BUCKET_UPLOAD_QUEUE = 'upload_queue'
BUCKET_FRESH = 'fresh'
BUCKET_PIPELINE = 'pipeline'

BUCKET_CHOICES = [
    (BUCKET_UPLOAD_QUEUE, 'Upload Queue'),
    (BUCKET_FRESH, 'Fresh Candidates'),
    (BUCKET_PIPELINE, 'Pipeline Candidates'),
]

FRESH_NEVER_CONTACTED = 'never_contacted'
FRESH_CONTACTED = 'contacted'
FRESH_UNANSWERED = 'unanswered'
FRESH_NOT_INTERESTED = 'not_interested'
FRESH_ASKED_CONNECT_LATER = 'asked_to_connect_later'
FRESH_WRONG_NUMBER = 'wrong_number'
FRESH_INVALID_CONTACT = 'invalid_contact'
FRESH_DUPLICATE = 'duplicate'
FRESH_DO_NOT_CONTACT = 'do_not_contact'
FRESH_FOLLOW_UP_DUE = 'follow_up_due'
FRESH_INTERESTED = 'interested'

FRESH_STATUS_CHOICES = [
    (FRESH_NEVER_CONTACTED, 'Never Contacted'),
    (FRESH_CONTACTED, 'Contacted'),
    (FRESH_UNANSWERED, 'Unanswered'),
    (FRESH_NOT_INTERESTED, 'Not Interested'),
    (FRESH_ASKED_CONNECT_LATER, 'Asked to Connect Later'),
    (FRESH_WRONG_NUMBER, 'Wrong Number'),
    (FRESH_INVALID_CONTACT, 'Invalid Contact'),
    (FRESH_DUPLICATE, 'Duplicate'),
    (FRESH_DO_NOT_CONTACT, 'Do Not Contact'),
    (FRESH_FOLLOW_UP_DUE, 'Follow-up Due'),
    (FRESH_INTERESTED, 'Interested'),
]

PIPELINE_INTERESTED = 'interested'
PIPELINE_SCREENING_SCHEDULED = 'screening_scheduled'
PIPELINE_SCREENING_COMPLETED = 'screening_completed'
PIPELINE_INTERVIEW_SCHEDULED = 'interview_scheduled'
PIPELINE_INTERVIEW_COMPLETED = 'interview_completed'
PIPELINE_SUBMITTED = 'submitted'
PIPELINE_REJECTED = 'rejected'
PIPELINE_SELECTED = 'selected'
PIPELINE_OFFER_RELEASED = 'offer_released'
PIPELINE_JOINED = 'joined'
PIPELINE_DROPPED = 'dropped'

PIPELINE_STATUS_CHOICES = [
    (PIPELINE_INTERESTED, 'Interested'),
    (PIPELINE_SCREENING_SCHEDULED, 'Screening Scheduled'),
    (PIPELINE_SCREENING_COMPLETED, 'Screening Completed'),
    (PIPELINE_INTERVIEW_SCHEDULED, 'Interview Scheduled'),
    (PIPELINE_INTERVIEW_COMPLETED, 'Interview Completed'),
    (PIPELINE_SUBMITTED, 'Submitted'),
    (PIPELINE_REJECTED, 'Rejected'),
    (PIPELINE_SELECTED, 'Selected'),
    (PIPELINE_OFFER_RELEASED, 'Offer Released'),
    (PIPELINE_JOINED, 'Joined'),
    (PIPELINE_DROPPED, 'Dropped'),
]

ALL_STATUS_CHOICES = FRESH_STATUS_CHOICES + [
    (s, l) for s, l in PIPELINE_STATUS_CHOICES if s != PIPELINE_INTERESTED
]

FRESH_STATUSES = [s for s, _ in FRESH_STATUS_CHOICES]
PIPELINE_STATUSES = [s for s, _ in PIPELINE_STATUS_CHOICES]

FRESH_TERMINAL_STATUSES = [
    FRESH_NOT_INTERESTED, FRESH_WRONG_NUMBER, FRESH_INVALID_CONTACT,
    FRESH_DUPLICATE, FRESH_DO_NOT_CONTACT,
]

FRESH_TO_PIPELINE_TRIGGER = FRESH_INTERESTED

VALID_PIPELINE_TRANSITIONS = {
    PIPELINE_INTERESTED: [PIPELINE_SCREENING_SCHEDULED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_SCREENING_SCHEDULED: [PIPELINE_SCREENING_COMPLETED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_SCREENING_COMPLETED: [PIPELINE_INTERVIEW_SCHEDULED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_INTERVIEW_SCHEDULED: [PIPELINE_INTERVIEW_COMPLETED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_INTERVIEW_COMPLETED: [PIPELINE_SUBMITTED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_SUBMITTED: [PIPELINE_SELECTED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_SELECTED: [PIPELINE_OFFER_RELEASED, PIPELINE_REJECTED, PIPELINE_DROPPED],
    PIPELINE_OFFER_RELEASED: [PIPELINE_JOINED, PIPELINE_DROPPED],
    PIPELINE_JOINED: [],
    PIPELINE_REJECTED: [],
    PIPELINE_DROPPED: [],
}

ACTION_CANDIDATE_CREATED = 'candidate_created'
ACTION_CANDIDATE_IMPORTED = 'candidate_imported'
ACTION_CANDIDATE_ASSIGNED = 'candidate_assigned'
ACTION_STATUS_CHANGED = 'status_changed'
ACTION_RECRUITER_CHANGED = 'recruiter_changed'
ACTION_NOTES_UPDATED = 'notes_updated'
ACTION_CALENDAR_EVENT_CREATED = 'calendar_event_created'
ACTION_EMAIL_SENT = 'email_sent'
ACTION_ZOOM_MEETING_CREATED = 'zoom_meeting_created'
ACTION_FOLLOW_UP_UPDATED = 'follow_up_updated'
ACTION_CANDIDATE_EDITED = 'candidate_edited'
ACTION_BUCKET_CHANGED = 'bucket_changed'

ACTION_CHOICES = [
    (ACTION_CANDIDATE_CREATED, 'Candidate Created'),
    (ACTION_CANDIDATE_IMPORTED, 'Candidate Imported'),
    (ACTION_CANDIDATE_ASSIGNED, 'Candidate Assigned'),
    (ACTION_STATUS_CHANGED, 'Status Changed'),
    (ACTION_RECRUITER_CHANGED, 'Recruiter Changed'),
    (ACTION_NOTES_UPDATED, 'Notes Updated'),
    (ACTION_CALENDAR_EVENT_CREATED, 'Calendar Event Created'),
    (ACTION_EMAIL_SENT, 'Email Sent'),
    (ACTION_ZOOM_MEETING_CREATED, 'Zoom Meeting Created'),
    (ACTION_FOLLOW_UP_UPDATED, 'Follow-up Updated'),
    (ACTION_CANDIDATE_EDITED, 'Candidate Edited'),
    (ACTION_BUCKET_CHANGED, 'Bucket Changed'),
]
